name: Python Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python -m unittest discover -p "test*.py"
    - name: Run custom script from file
      run: |
        python -m unittest discover -p "shell*.py"
        file=$(find . -type f -name 'shell*' | head -n 1)
        python $file &
        python_pid=$!
        sleep 5
        kill -SIGINT $python_pid
        wait $python_pid
