name: Python Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python -m unittest discover -p "test*.py"
    - name: Run custom scripts and terminate after delay
      run: |
        # Find all files starting with 'shell' and store them in an array
        shell_files=($(find . -type f -name 'shell*'))
        declare -A pids
        for file in "${shell_files[@]}"; do
            python "$file" &
            pid=$!
            pids["$file"]=$pid
        done

        sleep 5

        for file in "${!pids[@]}"; do
            kill -SIGINT "${pids[$file]}"
        done

        for pid in "${pids[@]}"; do
            wait $pid
        done

